name: API Test Pipeline

on:
  push:
    branches: [ main ]

jobs:

  contract-test:
    name: Contract Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run Contract Tests with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-contract.xml

      - name: Upload Contract Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: contract-test-report
          path: target/surefire-reports

  functional-test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: contract-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Run Functional Tests with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-functional.xml

      - name: Upload Functional Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: functional-test-report
          path: target/surefire-reports