name: API Test Pipeline

on:
  push:
    branches: [ main ]

jobs:
  healthcheck:
    name: HealthCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run HealthCheck with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-healthcheck.xml
      - name: Store Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-healthcheck
          path: target/allure-results
          retention-days: 1

  contract-test:
    name: Contract Test
    runs-on: ubuntu-latest
    needs: healthcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run Contract Tests with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-contract.xml
      - name: Store Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-contract
          path: target/allure-results
          retention-days: 1

  functional-test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: contract-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Run Functional Tests with Maven
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-functional.xml
      - name: Store Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-functional
          path: target/allure-results
          retention-days: 1

  generate-report:
    name: Generate Allure Report
    runs-on: ubuntu-latest
    needs: [healthcheck, contract-test, functional-test]
    if: always()
    steps:
      - name: Download all Allure results
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          pattern: allure-results-*
          merge-multiple: true
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1
        with:
          results_path: allure-results
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report